# Generated by Django 4.1 on 2023-10-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('descriptions', models.CharField(max_length=200)),
                ('dataFile', models.FileField(upload_to='app/files')),
            ],
        ),
    ]
